{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.pyamsoft.pydroid",
    "module": "bootstrap-play",
    "version": "30.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.pyamsoft.pydroid",
          "module": "bootstrap",
          "version": {
            "requires": "30.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "bootstrap-play-30.0.0.aar",
          "url": "bootstrap-play-30.0.0.aar",
          "size": 92232,
          "sha512": "182066e461e64fc2efe8419d759ef1f34368b33d603465c02bf3cb294ec64f33e65d4b8ac37add3cc73671ad7220e98224c02f6486f6d1fd389120f707969944",
          "sha256": "5dad2bf849dbfd715cf8d819524dc11beb056eb44dbb0265e285d57bba7d15dc",
          "sha1": "332c4a1c4d304d4d49cae7f19f87d458a94d42cb",
          "md5": "2dfba0a725a1dbf5456f97a43e18af95"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "app-update",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "review",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.github.pyamsoft.pydroid",
          "module": "bootstrap",
          "version": {
            "requires": "30.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "bootstrap-play-30.0.0.aar",
          "url": "bootstrap-play-30.0.0.aar",
          "size": 92232,
          "sha512": "182066e461e64fc2efe8419d759ef1f34368b33d603465c02bf3cb294ec64f33e65d4b8ac37add3cc73671ad7220e98224c02f6486f6d1fd389120f707969944",
          "sha256": "5dad2bf849dbfd715cf8d819524dc11beb056eb44dbb0265e285d57bba7d15dc",
          "sha1": "332c4a1c4d304d4d49cae7f19f87d458a94d42cb",
          "md5": "2dfba0a725a1dbf5456f97a43e18af95"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bootstrap-play-30.0.0-sources.jar",
          "url": "bootstrap-play-30.0.0-sources.jar",
          "size": 18289,
          "sha512": "6b5b4d5b4655d6c778678fe4ad4714e5a638647d4d412da42d421939fa05fdff61b3879efc2eae8c7fa7e53e34310b09353fbed0100a16f933c88049b6dadab5",
          "sha256": "e4ed50762cbbfd12a850cf27904de888fbe2cb162267ce58f1cc85ddd9981ca1",
          "sha1": "a19a72c23c18674a052cc06b2babae976dd9218b",
          "md5": "5f06b1c25b43f554e29cf3439b95773b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bootstrap-play-30.0.0-javadoc.jar",
          "url": "bootstrap-play-30.0.0-javadoc.jar",
          "size": 410709,
          "sha512": "56fc960c3dcec0b520a8f449686b94c3f2021c9b3ff719473716311e5384f34d9573237f4f3d906920d91e9784fe1261a7b259884e111ff2d7d325c75285d4c1",
          "sha256": "e8370a98afc4266ac817ed0e4e40272fb71fbe2d2f9b0b8057eabf042961c44e",
          "sha1": "638ee7d8abb776f83dc1239ae0389fae36af5473",
          "md5": "e08e75fc04ab28d0e567d9644385e5d9"
        }
      ]
    }
  ]
}
