{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.pyamsoft.pydroid",
    "module": "arch",
    "version": "30.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.pyamsoft.pydroid",
          "module": "bus",
          "version": {
            "requires": "30.0.0"
          }
        },
        {
          "group": "com.github.pyamsoft.pydroid",
          "module": "util",
          "version": {
            "requires": "30.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "arch-30.0.0.aar",
          "url": "arch-30.0.0.aar",
          "size": 10256,
          "sha512": "52ed60fc0828c4e8227718532a74ef64a2f54fe4196ce4cadfce6de07121da9db2484d48201734145287979bc4a2ce74d355516f7a7c3bd58935b2adef328991",
          "sha256": "73900799780c8eb65e79ffffb24fa50176cf3c894bcbdfbecc37e85689ad3aa9",
          "sha1": "6804b709a6cba4a1d6c203c71bc97b5f687fde56",
          "md5": "50f0ac53301108ffa8dcc508784c1cd9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.github.pyamsoft.pydroid",
          "module": "bus",
          "version": {
            "requires": "30.0.0"
          }
        },
        {
          "group": "com.github.pyamsoft.pydroid",
          "module": "util",
          "version": {
            "requires": "30.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "arch-30.0.0.aar",
          "url": "arch-30.0.0.aar",
          "size": 10256,
          "sha512": "52ed60fc0828c4e8227718532a74ef64a2f54fe4196ce4cadfce6de07121da9db2484d48201734145287979bc4a2ce74d355516f7a7c3bd58935b2adef328991",
          "sha256": "73900799780c8eb65e79ffffb24fa50176cf3c894bcbdfbecc37e85689ad3aa9",
          "sha1": "6804b709a6cba4a1d6c203c71bc97b5f687fde56",
          "md5": "50f0ac53301108ffa8dcc508784c1cd9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "arch-30.0.0-sources.jar",
          "url": "arch-30.0.0-sources.jar",
          "size": 5817,
          "sha512": "05f7c4931f0a1b1492e08075a329cd3faa329f12472fb0ed492601d59f121f0f8b8f875c4345430af7fd1a8e94798163503208ef98e7cbd82cf14cfa52f7ca5b",
          "sha256": "59c52fff7651632542985627948f1ca0c0fd810d7175e16d17fc0a373b7c97d3",
          "sha1": "5676e5c583a5bda04130e6ec4863bfc38c21d3c3",
          "md5": "fb91ff22d36622e79bc8b75061eb686a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "arch-30.0.0-javadoc.jar",
          "url": "arch-30.0.0-javadoc.jar",
          "size": 428029,
          "sha512": "605b43c731860e402f63c89a35a95adbab2d4eed6221961416069e96a99b0f7ade2c0299ec793b84010734662f2534b77846e85a7c6aa6ba279ebe33d45e01d3",
          "sha256": "011bb48e42ebf3b9781798d4d71b72dffdcd947dd78bc32f338e611ebe265638",
          "sha1": "ba658f40647be1cc74c5c800f40ae978e5bbae4d",
          "md5": "347d30515153cc6d79854daaf599fd1f"
        }
      ]
    }
  ]
}
