[versions]
# SDK
minSdk = "26"
targetSdk = "37"
compileSdk = "37"
# Android Gradle
agp = "9.4.0"
cacheFix = "3.0.3"
# Kotlin
kotlin = "2.4.20"
coroutines = "1.11.0"
# Us
pydroid = "29.6.0"
# Square
leakCanary = "2.14"
timber = "5.0.1"
qrCode = "4.5.0"
dagger = "2.60.1"
netty = "4.2.17.Final"
# Silence SLF4J logging warnings
slf4j = "2.0.19"
# AndroidX
core = "1.19.0"
activity = "1.13.0"
lifecycle = "2.11.0"
dataStore = "1.2.1"
preference = "1.2.1"
testRunner = "1.7.0"
# Compose
compose = "1.12.0"
composeMaterial3 = "1.4.0"
# Google
ksp = "2.3.11"
# Images
coil = "3.6.2"
# Developer Tools
ktfmt = "0.64"
spotless = "8.10.2"
jdkDesugar = "2.1.5"
caupain = "1.10.1"
detekt = "2.0.0-alpha.6"
# Testing
junit = "4.13.2"
robolectric = "4.16.1"
