{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.pyamsoft.pydroid",
    "module": "bootstrap-noop",
    "version": "30.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.pyamsoft.pydroid",
          "module": "bootstrap",
          "version": {
            "requires": "30.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "bootstrap-noop-30.0.0.aar",
          "url": "bootstrap-noop-30.0.0.aar",
          "size": 7743,
          "sha512": "26ce7ce8a014cf39f89553f4fb49250d21a9efe7712086c3c058c5490bfd196c938e0a89293f58f787bfc17a928aa427c15eb3d3d6765dd49b7c530891973687",
          "sha256": "4c1e5f035fe260d24f0ee405a9729b7ceb0b023159284a1d72c651c112017864",
          "sha1": "0a080bfbda01e5e07976c9a8285cc43b325f3794",
          "md5": "14b5a6b2ac804ab7c03c3d4d3966de9f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.github.pyamsoft.pydroid",
          "module": "bootstrap",
          "version": {
            "requires": "30.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "bootstrap-noop-30.0.0.aar",
          "url": "bootstrap-noop-30.0.0.aar",
          "size": 7743,
          "sha512": "26ce7ce8a014cf39f89553f4fb49250d21a9efe7712086c3c058c5490bfd196c938e0a89293f58f787bfc17a928aa427c15eb3d3d6765dd49b7c530891973687",
          "sha256": "4c1e5f035fe260d24f0ee405a9729b7ceb0b023159284a1d72c651c112017864",
          "sha1": "0a080bfbda01e5e07976c9a8285cc43b325f3794",
          "md5": "14b5a6b2ac804ab7c03c3d4d3966de9f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bootstrap-noop-30.0.0-sources.jar",
          "url": "bootstrap-noop-30.0.0-sources.jar",
          "size": 6179,
          "sha512": "3c8686fb6234036f43c79881de7ba1470f485e536c71a6037f9654a8e9589b218c0fcb28bb3593c530292362cc13109a041dedcd0534869bebd79a14a255ed92",
          "sha256": "a628e31633ded1d346fe890d6d027632b1e4135eed62fe7e3fe8ffee9bdd6890",
          "sha1": "c500361c926117d6bb6261e3eced27e0910931fa",
          "md5": "fb21c2898896f85d8291eeef4d620110"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bootstrap-noop-30.0.0-javadoc.jar",
          "url": "bootstrap-noop-30.0.0-javadoc.jar",
          "size": 412330,
          "sha512": "58b70a2e1952c7bcbb26ee86f02329d67e254a03b66467795342864248d2d5afc8046a079e19df8d06589d07d6374cc7966cfff4d5b55b790b54df210fe4f00d",
          "sha256": "5b40ea4db511e8b05abddc73eba59a790a7d1e4c6ba3881701e4119ea0bf89d2",
          "sha1": "6affb80dafa4b307c10b726247c26e1590329888",
          "md5": "216bc12ae5213bae57649747721941b1"
        }
      ]
    }
  ]
}
