{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.pyamsoft.pydroid",
    "module": "billing-play",
    "version": "30.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.pyamsoft.pydroid",
          "module": "billing",
          "version": {
            "requires": "30.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "billing-play-30.0.0.aar",
          "url": "billing-play-30.0.0.aar",
          "size": 30671,
          "sha512": "9537b5c8484b20ecb44bdb04a1987a1564379b68785f7ed123c753b0870430390a078f0a59af0da74eaa9d8040ca88a30fc03d1b0891cfdcf8566f14460c333d",
          "sha256": "ee6819468a416e2e11b35438a388c40803a904688663bbfa9a57c338b3ba4eb2",
          "sha1": "4b14aec6603430eeb7321b3ffc41cd7f43ec5f5a",
          "md5": "89997ae91cd402919b51057fd3ce3710"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.android.billingclient",
          "module": "billing",
          "version": {
            "requires": "9.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.github.pyamsoft.pydroid",
          "module": "billing",
          "version": {
            "requires": "30.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "billing-play-30.0.0.aar",
          "url": "billing-play-30.0.0.aar",
          "size": 30671,
          "sha512": "9537b5c8484b20ecb44bdb04a1987a1564379b68785f7ed123c753b0870430390a078f0a59af0da74eaa9d8040ca88a30fc03d1b0891cfdcf8566f14460c333d",
          "sha256": "ee6819468a416e2e11b35438a388c40803a904688663bbfa9a57c338b3ba4eb2",
          "sha1": "4b14aec6603430eeb7321b3ffc41cd7f43ec5f5a",
          "md5": "89997ae91cd402919b51057fd3ce3710"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "billing-play-30.0.0-sources.jar",
          "url": "billing-play-30.0.0-sources.jar",
          "size": 6398,
          "sha512": "8aed07b13b1acee1279085ec14eb57749f4b1b76c20289e5e03f4980cdc8f69a070528cd842e97baf505ac57aaec4ee53a9723b9034366b482e4d4ede8bbf855",
          "sha256": "c81cb8006513ef3616eafcf2e5aa7f594a77c5d4280f3e0f327234771fdf4a83",
          "sha1": "42fe6cf0a470c54ebcd2226473964a0bfba1719d",
          "md5": "fc1bcac0d8784926011120fefc85189d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "billing-play-30.0.0-javadoc.jar",
          "url": "billing-play-30.0.0-javadoc.jar",
          "size": 405169,
          "sha512": "4a706b6f5e3595d96ccb6219ceb5ef3055be55e382944eb515a3e9c412c6945db1e1cd9694c6603b0fd2789743d0ead03dd06ef23011ef0f66f594735c1530fa",
          "sha256": "91a592718b7bce73bedf50d6ed46d469f179d40e67396695dfe0bf5b8a88c7fb",
          "sha1": "68f2b1fb782c88c4d85c628225ba985fd47f3b95",
          "md5": "d60d640c08a7ecfd9433e9b1acca8945"
        }
      ]
    }
  ]
}
