{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.pyamsoft.pydroid",
    "module": "notify",
    "version": "30.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.pyamsoft.pydroid",
          "module": "util",
          "version": {
            "requires": "30.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "notify-30.0.0.aar",
          "url": "notify-30.0.0.aar",
          "size": 19272,
          "sha512": "5c121f1e8fc361a8cb684b16bcad3680823aec5660b9a59feffe8993c661f6fc748442fe72cc150bbe5e13e28895c340e5e740055325442025104ca8a2b7a847",
          "sha256": "441ca554bc2aa8b25a5b69d7c489772bc27a53af36a42af2bc7f48ab28b7e2eb",
          "sha1": "13832aa8b6b527577e4ad85ec7a33d8b59abb953",
          "md5": "a82a54409fee1759ba8758364d58ee19"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "com.github.pyamsoft.pydroid",
          "module": "util",
          "version": {
            "requires": "30.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "notify-30.0.0.aar",
          "url": "notify-30.0.0.aar",
          "size": 19272,
          "sha512": "5c121f1e8fc361a8cb684b16bcad3680823aec5660b9a59feffe8993c661f6fc748442fe72cc150bbe5e13e28895c340e5e740055325442025104ca8a2b7a847",
          "sha256": "441ca554bc2aa8b25a5b69d7c489772bc27a53af36a42af2bc7f48ab28b7e2eb",
          "sha1": "13832aa8b6b527577e4ad85ec7a33d8b59abb953",
          "md5": "a82a54409fee1759ba8758364d58ee19"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "notify-30.0.0-sources.jar",
          "url": "notify-30.0.0-sources.jar",
          "size": 9326,
          "sha512": "045cc74a487d7d95c6da81b7c78e5b2fcfb5995c19a5e365ebd977d2fee24ed766e89fa2ad8111b0324a441423c19f150fdb4020ab3649a7791aa0dd354d91c4",
          "sha256": "e645f57ac1352c2cf11a16865c219371b3fe45743151b5b29a8b4c5a9cb4d065",
          "sha1": "cdbcad35a1ca1a69ef83bbdbeb91dabe47389deb",
          "md5": "a3d89afce22ee41767ae730a09bdace2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "notify-30.0.0-javadoc.jar",
          "url": "notify-30.0.0-javadoc.jar",
          "size": 455292,
          "sha512": "295778ef51d2167599fc18419f948a394ba7060d097d20b9a4fea81167d42487ebf8e76986f0039e12c9f465f7d16b68c5d01c626e56357f3f72cf9b181c5c72",
          "sha256": "699e57f4499f26f4a88476d5d0265fbd4265a6b312e0ea7ba78e6c787c427a21",
          "sha1": "1dd79892b81a1a02fc4c7c5951b35d37fa710b68",
          "md5": "b0c864d2bd574d273f5bf5c1a5b860e8"
        }
      ]
    }
  ]
}
