name: OFFLINE VENDOR 1ST TIME
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Vendor pydroid to local-repo
        run: |
          curl -L https://github.com/pyamsoft/pydroid/archive/refs/tags/30.0.0.zip -o p.zip
          unzip p.zip
          cd pydroid-30.0.0
          chmod +x gradlew
          ./gradlew publish -PpublishUrl=file://${{ github.workspace }}/local-repo --no-configuration-cache -Dorg.gradle.parallel=false
          cd ..
          rm -rf pydroid-30.0.0 p.zip .gradle

      - name: Commit ALL to make offline
        run: |
          git config user.name "bot"
          git config user.email "bot@bot.com"
          git add -f local-repo
          git commit -m "offline vendor done" || echo "nothing"
          git push
